CREATE DATABASE IF NOT EXISTS farmacia1;
USE farmacia1;


-- Tabela de Usuários
CREATE TABLE usuarios (
    id INT NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR
    nome VARCHAR(100) NOT NULL, -- NOME DE LOGIN DA FARMACIA
    senha VARCHAR(255) NOT NULL, -- SENHA DE LOGIN DA FARMACIA
    cargo VARCHAR(50) NOT NULL, -- ADMINISTRADOR OU USUARIO
    PRIMARY KEY (id) 
);

-- Tabela de Produtos
CREATE TABLE produtos (
    id INT NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR
    nome VARCHAR(150) NOT NULL, -- NOME DO MEDICAMENTO
    descricao TEXT NOT NULL, -- DESCRIÇÃO DO PRODUTO
    preco DECIMAL(10,2) NOT NULL, -- PREÇPO DE VENDA
    quantidade INT NOT NULL, -- QUANTIDADE DISPONIVEL
    estoque_minimo INT NOT NULL, -- LIMITE PARA EMITIR O ALERTA
    imagem VARCHAR(255) NOT NULL, -- CAMINHO DA IMAGEM
    criado_em DATETIME NOT NULL, -- DATA DO CADASTRO
    PRIMARY KEY (id)
);

-- Tabela de Lotes
CREATE TABLE lotes (
    id INT NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR
    produto_id INT NOT NULL, -- PRODUTO RELACIONADO
    numero_lote VARCHAR(50) NOT NULL, -- NÚMERO DO LOTE
    quantidade INT NOT NULL, -- QUANTIDADE NESSE LOTE
    validade DATE NOT NULL, -- DATA DE VALIDADE
    data_entrada DATETIME NOT NULL, -- DATA DE REBIMENTO 
    PRIMARY KEY (id)
);

-- Tabela de Vendas
CREATE TABLE vendas (
    id INT NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR
    usuario_id INT NOT NULL, -- FUNCIONARIO RESPONSAVEL
    valor_total DECIMAL(10,2) NOT NULL, -- TOTAL DA VENDA 
    forma_pagamento VARCHAR(50) NOT NULL, -- PIX, DINHEIRO E CARTÃO
    data_venda DATETIME NOT NULL, -- DATA DA VENDA
    PRIMARY KEY (id)
);

-- Tabela de Itens da Venda
CREATE TABLE itens_venda (
    id INT NOT NULL AUTO_INCREMENT, -- IDENTIFICADOR
    venda_id INT NOT NULL, -- VENDA RELACIONADA 
    produto_id INT NOT NULL, -- PRODUTO RELACIONADO 
    quantidade INT NOT NULL, -- QUANTIDADE VENDIDA 
    preco_unitario DECIMAL(10,2) NOT NULL, -- PREÇO NO MOMENTO DA VENDA 
    subtotal DECIMAL(10,2) NOT NULL, -- TOTAL DA VENDA
    PRIMARY KEY (id)
);