<?php
session_start(); require_once __DIR__.'/../autenticacao.php'; require_once __DIR__.'/../gerente/conexaoDB.php'; require_once __DIR__.'/../includes/auditoria.php'; exigirLogin('balconista');
$farmaciaId=(int)$_SESSION['farmacia_id'];$usuarioId=(int)$_SESSION['usuario_id'];$carrinho=$_SESSION['carrinho']??array(); if(!$carrinho){header('Location: carrinhobalconista.php?erro=Carrinho vazio');exit;}$formaPagamento=$_POST['forma_pagamento']??'';if(!in_array($formaPagamento,array('dinheiro','pix','debito','credito'),true)){header('Location: carrinhobalconista.php?erro=Pagamento invalido');exit;}$cliente=trim($_POST['cliente']??'')?:null;$cpfCliente=preg_replace('/\D/','',$_POST['cpf_cliente']??'');$cpfCliente=$cpfCliente===''?null:$cpfCliente;if($cpfCliente!==null&&strlen($cpfCliente)!==11){header('Location: carrinhobalconista.php?erro='.urlencode('O CPF deve ter 11 números.'));exit;}
$itens=array();$total=0;mysqli_begin_transaction($conexao);try{foreach($carrinho as $produtoId=>$quantidade){$produtoId=(int)$produtoId;$quantidade=(int)$quantidade;$stmt=mysqli_prepare($conexao,"SELECT p.nome,p.preco,p.quantidade,COALESCE(SUM(l.quantidade),0) lote_total,COALESCE(SUM(CASE WHEN l.validade>=CURDATE() THEN l.quantidade ELSE 0 END),0) lote_valido FROM produtos p LEFT JOIN lotes l ON l.produto_id=p.id WHERE p.id=? AND p.farmacia_id=? AND p.ativo=1 GROUP BY p.id,p.nome,p.preco,p.quantidade FOR UPDATE");mysqli_stmt_bind_param($stmt,'ii',$produtoId,$farmaciaId);mysqli_stmt_execute($stmt);$produto=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt));$disponivel=$produto?max(0,(int)$produto['quantidade']-(int)$produto['lote_total'])+(int)$produto['lote_valido']:0;if(!$produto||$quantidade<1||$quantidade>$disponivel)throw new Exception('Estoque disponível insuficiente ou lote vencido.');$preco=(float)$produto['preco'];$subtotal=$preco*$quantidade;$total+=$subtotal;$itens[]=array('produto_id'=>$produtoId,'quantidade'=>$quantidade,'preco'=>$preco,'subtotal'=>$subtotal);}
$valorRecebido=$formaPagamento==='dinheiro'?(float)($_POST['valor_recebido']??0):$total;if($valorRecebido<$total)throw new Exception('Valor recebido insuficiente.');$troco=$valorRecebido-$total;$stmt=mysqli_prepare($conexao,'INSERT INTO vendas (farmacia_id,usuario_id,cliente,cpf_cliente,valor_total,valor_recebido,troco,forma_pagamento) VALUES (?,?,?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'iissddds',$farmaciaId,$usuarioId,$cliente,$cpfCliente,$total,$valorRecebido,$troco,$formaPagamento);mysqli_stmt_execute($stmt);$vendaId=mysqli_insert_id($conexao);
foreach($itens as $item){$produtoId=$item['produto_id'];$quantidade=$item['quantidade'];$preco=$item['preco'];$subtotal=$item['subtotal'];$stmt=mysqli_prepare($conexao,'INSERT INTO itens_venda (venda_id,produto_id,quantidade,preco_unitario,subtotal) VALUES (?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'iiidd',$vendaId,$produtoId,$quantidade,$preco,$subtotal);mysqli_stmt_execute($stmt);$itemId=mysqli_insert_id($conexao);
$restante=$quantidade;$stmt=mysqli_prepare($conexao,"SELECT id,quantidade FROM lotes WHERE farmacia_id=? AND produto_id=? AND quantidade>0 AND validade>=CURDATE() ORDER BY validade ASC,id ASC FOR UPDATE");mysqli_stmt_bind_param($stmt,'ii',$farmaciaId,$produtoId);mysqli_stmt_execute($stmt);$lotes=mysqli_stmt_get_result($stmt);while($restante>0&&($l=mysqli_fetch_assoc($lotes))){$usar=min($restante,(int)$l['quantidade']);$loteId=(int)$l['id'];$stmt2=mysqli_prepare($conexao,'UPDATE lotes SET quantidade=quantidade-? WHERE id=?');mysqli_stmt_bind_param($stmt2,'ii',$usar,$loteId);mysqli_stmt_execute($stmt2);$stmt2=mysqli_prepare($conexao,'INSERT INTO itens_venda_lotes (item_venda_id,lote_id,quantidade) VALUES (?,?,?)');mysqli_stmt_bind_param($stmt2,'iii',$itemId,$loteId,$usar);mysqli_stmt_execute($stmt2);$restante-=$usar;}
$stmt=mysqli_prepare($conexao,'UPDATE produtos SET quantidade=quantidade-? WHERE id=? AND farmacia_id=?');mysqli_stmt_bind_param($stmt,'iii',$quantidade,$produtoId,$farmaciaId);mysqli_stmt_execute($stmt);$tipo='saida';$obs='Venda #'.$vendaId;$stmt=mysqli_prepare($conexao,'INSERT INTO movimentacoes_estoque (farmacia_id,produto_id,usuario_id,tipo,quantidade,observacao) VALUES (?,?,?,?,?,?)');mysqli_stmt_bind_param($stmt,'iiisis',$farmaciaId,$produtoId,$usuarioId,$tipo,$quantidade,$obs);mysqli_stmt_execute($stmt);}
registrarAuditoria($conexao,'finalizar','venda',$vendaId,'Venda concluída no valor de R$ '.number_format($total,2,',','.'));mysqli_commit($conexao);$_SESSION['carrinho']=array();header('Location: recibobalconista.php?id='.$vendaId);exit;}catch(Throwable $e){mysqli_rollback($conexao);header('Location: carrinhobalconista.php?erro='.urlencode($e->getMessage()));exit;}
